version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
