version: '3.8'

services:
  async_api:
    build: ./async-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
  sync_api:
    build: ./sync-api
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
